CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS sites_ping;

CREATE TABLE sites_ping (
    ID UUID PRIMARY KEY,
    site VARCHAR(255) NOT NULL,
    ping INT NOT NULL
);

INSERT INTO sites_ping VALUES
(uuid_generate_v4(), 'google.com', 0),
(uuid_generate_v4(), 'youtube.com', 0),
(uuid_generate_v4(), 'facebook.com', 0),
(uuid_generate_v4(), 'baidu.com', 0),
(uuid_generate_v4(), 'wikipedia.org', 0),
(uuid_generate_v4(), 'qq.com', 0),
(uuid_generate_v4(), 'taobao.com', 0),
(uuid_generate_v4(), 'yahoo.com', 0),
(uuid_generate_v4(), 'tmall.com', 0),
(uuid_generate_v4(), 'amazon.com', 0),
(uuid_generate_v4(), 'google.co.in', 0),
(uuid_generate_v4(), 'twitter.com', 0),
(uuid_generate_v4(), 'sohu.com', 0),
(uuid_generate_v4(), 'jd.com', 0),
(uuid_generate_v4(), 'live.com', 0),
(uuid_generate_v4(), 'instagram.com', 0),
(uuid_generate_v4(), 'sina.com.cn', 0),
(uuid_generate_v4(), 'weibo.com', 0),
(uuid_generate_v4(), 'google.co.jp', 0),
(uuid_generate_v4(), 'reddit.com', 0),
(uuid_generate_v4(), 'vk.com', 0),
(uuid_generate_v4(), '360.cn', 0),
(uuid_generate_v4(), 'login.tmall.com', 0),
(uuid_generate_v4(), 'blogspot.com', 0),
(uuid_generate_v4(), 'yandex.ru', 0),
(uuid_generate_v4(), 'google.com.hk', 0),
(uuid_generate_v4(), 'netflix.com', 0),
(uuid_generate_v4(), 'linkedin.com', 0),
(uuid_generate_v4(), 'pornhub.com', 0),
(uuid_generate_v4(), 'google.com.br', 0),
(uuid_generate_v4(), 'twitch.tv', 0),
(uuid_generate_v4(), 'pages.tmall.com', 0),
(uuid_generate_v4(), 'csdn.net', 0),
(uuid_generate_v4(), 'yahoo.co.jp', 0),
(uuid_generate_v4(), 'mail.ru', 0),
(uuid_generate_v4(), 'aliexpress.com', 0),
(uuid_generate_v4(), 'alipay.com', 0),
(uuid_generate_v4(), 'office.com', 0),
(uuid_generate_v4(), 'google.fr', 0),
(uuid_generate_v4(), 'google.ru', 0),
(uuid_generate_v4(), 'google.co.uk', 0),
(uuid_generate_v4(), 'microsoftonline.com', 0),
(uuid_generate_v4(), 'google.de', 0),
(uuid_generate_v4(), 'ebay.com', 0),
(uuid_generate_v4(), 'microsoft.com', 0),
(uuid_generate_v4(), 'livejasmin.com', 0),
(uuid_generate_v4(), 't.co', 0),
(uuid_generate_v4(), 'bing.com', 0),
(uuid_generate_v4(), 'xvideos.com', 0),
(uuid_generate_v4(), 'google.ca', 0);